### PR TITLE
Support for heroku-18 stack and update FreeTDS version

### PR DESCRIPTION
**Pull request by roshan92**

### CODE REVIEW

**Comment by fskuteken** [comment]
We are using a build from this branch (`roshan92:master`) in production, because the current `rails-sqlserver:master` branch is not working with our heroku-18 stack.

**Comment by RaresSalcudean** [comment]
Any updates on merging this PR?

**Comment by bf4** [comment]
I am so sorry I never saw these

**Comment by bf4** [comment]
Closed by https://github.com/rails-sqlserver/heroku-buildpack-freetds/pull/8

**Pull request closed without merging**
